name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Install Task
        uses: arduino/setup-task@v1
        with:
          version: 3.15.2

      - name: Test
        run: task test

      - name: Build
        run: task build
